OrdererOrgs:
  - Name: Orderer
    Domain: drugchain.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: ViePharmaCorp
    Domain: viepharmacorp.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: FeedexCorp
    Domain: feedexcorp.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: CircleH
    Domain: circleh.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: AuthorityOrg
    Domain: auditor.gov.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
