# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

services:
  orderer.drugchain.com:
    container_name: orderer.drugchain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/drugchain.com/orderers/orderer.drugchain.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/drugchain.com/orderers/orderer.drugchain.com/tls/:/var/hyperledger/orderer/tls
      - orderer.drugchain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.viepharmacorp.com:
    container_name: peer0.viepharmacorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.viepharmacorp.com
      - CORE_PEER_ADDRESS=peer0.viepharmacorp.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.viepharmacorp.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.viepharmacorp.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.viepharmacorp.com:7051
      - CORE_PEER_LOCALMSPID=ViePharmaCorpMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer0.viepharmacorp.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer0.viepharmacorp.com/tls:/etc/hyperledger/fabric/tls
      - peer0.viepharmacorp.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.viepharmacorp.com:
    container_name: peer1.viepharmacorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.viepharmacorp.com
      - CORE_PEER_ADDRESS=peer1.viepharmacorp.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.viepharmacorp.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.viepharmacorp.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.viepharmacorp.com:7051
      - CORE_PEER_LOCALMSPID=ViePharmaCorpMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer1.viepharmacorp.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer1.viepharmacorp.com/tls:/etc/hyperledger/fabric/tls
      - peer1.viepharmacorp.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.feedexcorp.com:
    container_name: peer0.feedexcorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.feedexcorp.com
      - CORE_PEER_ADDRESS=peer0.feedexcorp.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.feedexcorp.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.feedexcorp.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.feedexcorp.com:10051
      - CORE_PEER_LOCALMSPID=FeedexCorpMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/feedexcorp.com/peers/peer0.feedexcorp.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/feedexcorp.com/peers/peer0.feedexcorp.com/tls:/etc/hyperledger/fabric/tls
      - peer0.feedexcorp.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.feedexcorp.com:
    container_name: peer1.feedexcorp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.feedexcorp.com
      - CORE_PEER_ADDRESS=peer1.feedexcorp.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.feedexcorp.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.feedexcorp.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.feedexcorp.com:9051
      - CORE_PEER_LOCALMSPID=FeedexCorpMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/feedexcorp.com/peers/peer1.feedexcorp.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/feedexcorp.com/peers/peer1.feedexcorp.com/tls:/etc/hyperledger/fabric/tls
      - peer1.feedexcorp.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.circleh.com:
    container_name: peer0.circleh.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.circleh.com
      - CORE_PEER_ADDRESS=peer0.circleh.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.circleh.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.circleh.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.circleh.com:11051
      - CORE_PEER_LOCALMSPID=CircleHMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/circleh.com/peers/peer0.circleh.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/circleh.com/peers/peer0.circleh.com/tls:/etc/hyperledger/fabric/tls
      - peer0.circleh.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.circleh.com:
    container_name: peer1.circleh.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.circleh.com
      - CORE_PEER_ADDRESS=peer1.circleh.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.circleh.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.circleh.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.circleh.com:11051
      - CORE_PEER_LOCALMSPID=CircleHMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/circleh.com/peers/peer1.circleh.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/circleh.com/peers/peer1.circleh.com/tls:/etc/hyperledger/fabric/tls
      - peer1.circleh.com:/var/hyperledger/production

    ports:
      - 12051:12051

  peer0.auditor.gov.com:
    container_name: peer0.auditor.gov.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.auditor.gov.com
      - CORE_PEER_ADDRESS=peer0.auditor.gov.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.auditor.gov.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.auditor.gov.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.auditor.gov.com:13051
      - CORE_PEER_LOCALMSPID=AuthorityOrgMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/auditor.gov.com/peers/peer0.auditor.gov.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/auditor.gov.com/peers/peer0.auditor.gov.com/tls:/etc/hyperledger/fabric/tls
      - peer0.auditor.gov.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer1.auditor.gov.com:
    container_name: peer1.auditor.gov.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.auditor.gov.com
      - CORE_PEER_ADDRESS=peer1.auditor.gov.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.auditor.gov.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.auditor.gov.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.auditor.gov.com:13051
      - CORE_PEER_LOCALMSPID=AuthorityOrgMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/auditor.gov.com/peers/peer1.auditor.gov.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/auditor.gov.com/peers/peer1.auditor.gov.com/tls:/etc/hyperledger/fabric/tls
      - peer1.auditor.gov.com:/var/hyperledger/production

    ports:
      - 14051:14051
  # peer2.viepharmacorp.com:
  #   container_name: peer2.viepharmacorp.com
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer2.viepharmacorp.com
  #     - CORE_PEER_ADDRESS=peer2.viepharmacorp.com:15051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
  #     - CORE_PEER_CHAINCODEADDRESS=peer1.viepharmacorp.com:15052
  #     - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.viepharmacorp.com:15051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.viepharmacorp.com:7051
  #     - CORE_PEER_LOCALMSPID=ViePharmaCorpMSP
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer1.viepharmacorp.com/msp:/etc/hyperledger/fabric/msp
  #     - ../crypto-config/peerOrganizations/viepharmacorp.com/peers/peer1.viepharmacorp.com/tls:/etc/hyperledger/fabric/tls
  #     - peer1.viepharmacorp.com:/var/hyperledger/production
  #   ports:
  #     - 15051:15051
